C:\Users\39340\Documents\GitHub\in-context-bldc\data\simulated
C:\Users\39340\Documents\GitHub\in-context-bldc\data\simulated\experiment_2024-11-11_14:54:24_0.csv
Traceback (most recent call last):
  File "c:\Users\39340\Documents\GitHub\in-context-bldc\speed_estimator\bldc_simulator_CL_Ome.py", line 135, in <module>
    main()
  File "c:\Users\39340\Documents\GitHub\in-context-bldc\speed_estimator\bldc_simulator_CL_Ome.py", line 98, in main
    df.to_csv(obj_path, index=False)
  File "C:\Users\39340\AppData\Roaming\Python\Python312\site-packages\pandas\util\_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\39340\AppData\Roaming\Python\Python312\site-packages\pandas\core\generic.py", line 3961, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\39340\AppData\Roaming\Python\Python312\site-packages\pandas\io\formats\format.py", line 1014, in to_csv
    csv_formatter.save()
  File "C:\Users\39340\AppData\Roaming\Python\Python312\site-packages\pandas\io\formats\csvs.py", line 251, in save
    with get_handle(
         ^^^^^^^^^^^
  File "C:\Users\39340\AppData\Roaming\Python\Python312\site-packages\pandas\io\common.py", line 873, in get_handle
    handle = open(
             ^^^^^
OSError: [Errno 22] Invalid argument: 'C:\\Users\\39340\\Documents\\GitHub\\in-context-bldc\\data\\simulated\\experiment_2024-11-11_14:54:24_0.csv'
